[package]
name = "oxwalk"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.98"
chrono = "0.4.41"
clap = "4.5.38"
fastrand = "2.3.0"
fastrand-contrib = "0.1.0"
glam = "0.30.3"
plotters = "0.3.7"
